name: Expose the Admin Register pages
on:
  repository_dispatch:
    types: 
      - deploy

  workflow_dispatch:
    

jobs:
  get-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: robinraju/release-downloader@v1.6
        with: 
          repository: "saturngroup/solution-monorepo"
          fileName: "admin-register-pages"
          latest: true
          token: "${{ secrets.DOWNLOAD_TOKEN }}"

      - run: |
          ls -als
          tar xzvf admin-register-pages .
          rm admin-register-pages
          ls -als

      - run: |
          git add .
          git commit -m "Updating pages"
          git config --global user.email "${{ github.actor }}@runner.org"
          git config --global user.name "${{ github.actor }}"
          git push


    
